// Dữ liệu trả về từ API (response)
export interface InventoryItem {
  DIVISION_CD: string;
  DIVISION_NM: string;
  PRODUCTKIND_CD: string;
  PRODUCTKIND_NM: string;
  PRODUCTKIND_NM_ENG: string;
  PRODUCTKIND_NM_KOR: string;
  PRODUCTKIND_NM_CHINA: string;
  PTK_SORT: number;
  DEPARTMENT_CD: string;
  DEPARTMENT_USER_CD: string | null;
  DEP_NAME_KOR: string;
  DEP_NAME_ENG: string;
  DEP_NAME_VIET: string;
  DEP_NAME_JAPAN: string;
  DEP_NAME_CHINA: string;
  PRODUCT_CD: string;
  PRODUCT_NM: string;
  PRODUCT_NM_ENG: string;
  PRODUCT_NM_KOR: string;
  PRODUCT_NM_CHINA: string;
  PRODUCT_CODE: string;
  MR_CD: string;
  INBOUND_UNIT: string;
  IN_UNIT: string | null;
  OUTBOUND_UNIT: string;
  OUT_UNIT: string | null;
  MATERIALINPUT_UNIT: string;
  MATERIALUNIT_UNIT: string | null;
  STOCK_UNIT: string;
  STOCKUNIT: string;
  STORE_CD: string;
  STORE_NM: string | null;
  STORE_NM_ENG: string | null;
  STORE_NM_KOR: string | null;
  STORE_NM_CHINA: string | null;
  FITNESS_STOCK: number;
  STANDARD_CD: string;
  STANDARD_NM: string | null;
  UNIT_PRICE_CC: number;
  UNIT_PRICE_FC: number;
  EX_RATE: number;
  SUMMARY: string;
  ISUSE: string;
  USERID: string;
  CC_TYPE: string;
  FC_TYPE: string;
  INBOUND_QUANTITY: number | null;
  OUTBOUND_QUANTITY: number | null;
  MATERIALINPUT_QUANTITY: number | null;
  ORIGIN: string;
  AUDIT_NOTE: string;
  VAT_RATE: number;
}